# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals win-docker

variables:
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform 
    value: 'Any CPU'
  - name: buildConfiguration 
    value: 'Release'
  - group: demo-iis

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  inputs:
    solution: $(solution)
    configuration: $(buildConfiguration)
    msbuildLocationMethod: 'version'
    msbuildArguments: '/t:Rebuild /p:Configuration=Release /p:outdir=".\publish1\\"'

- script: dir /p


- task: PowerShell@2
  displayName: 'copy files'
  env:
    USER: $(USERNAME)
    PWD: $(PASSWORD)
  inputs:
    targetType: 'inline'
    script: |
      
       foreach($servidor in [System.IO.File]::ReadLines(".\servidores.txt"))
       {

           #Convert to SecureString
           [securestring]$secStringPassword = ConvertTo-SecureString $env:PWD -AsPlainText -Force

           [pscredential]$credObject = New-Object System.Management.Automation.PSCredential ($env:USER, $secStringPassword)

           $LocalPath =  ".\demo\publish1\_PublishedWebsites\demo"
           $RemotePath = "C:\publish1"

           $TargetSession = New-PSSession -ComputerName $servidor -Credential $credObject

           Invoke-Command -ToSession $TargetSession -ScriptBlock {Stop-WebAppPool -Name demo.iis}

           Copy-Item -Path $LocalPath -Destination $RemotePath -ToSession $TargetSession -Force -Recurs

           Invoke-Command -ToSession $TargetSession -ScriptBlock {Start-WebAppPool -Name demo.iis}
       
       }
